version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: smart_wardrobe_db
    restart: always
    environment:
      POSTGRES_USER: smartwardrobe
      POSTGRES_PASSWORD: smartwardrobe123
      POSTGRES_DB: smart_wardrobe_ai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
