"""Phase 9 schemas

Revision ID: 47c5a93639ee
Revises: ff971375d273
Create Date: 2026-06-18 00:24:34.383043
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c5a93639ee'
down_revision: Union[str, None] = 'ff971375d273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wear_events',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('wear_group_id', sa.UUID(), nullable=False),
    sa.Column('clothing_item_id', sa.UUID(), nullable=False),
    sa.Column('worn_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.Enum('MANUAL', 'RECOMMENDATION', 'DAILY_STYLIST', 'SAVED_OUTFIT', name='wearsourcetype'), nullable=False),
    sa.Column('occasion', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('weather_snapshot', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.ForeignKeyConstraint(['clothing_item_id'], ['clothing_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wear_events_wear_group_id'), 'wear_events', ['wear_group_id'], unique=False)
    op.create_index(op.f('ix_wear_events_worn_at'), 'wear_events', ['worn_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wear_events_worn_at'), table_name='wear_events')
    op.drop_index(op.f('ix_wear_events_wear_group_id'), table_name='wear_events')
    op.drop_table('wear_events')
    # ### end Alembic commands ###
