"""add ai_plan to users

Revision ID: 4d4ae2474b87
Revises: 1ca6e840fb6a
Create Date: 2026-06-21 01:52:36.754098
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d4ae2474b87'
down_revision: Union[str, None] = '1ca6e840fb6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ai_plan', sa.String(length=50), server_default='free', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_plan')
    # ### end Alembic commands ###
