"""Add feed category and confidence to intelligence feed, add InsightQualityMetric

Revision ID: 1a16a3b02411
Revises: 083b36f71708
Create Date: 2026-06-16 00:21:31.559709
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a16a3b02411'
down_revision: Union[str, None] = '083b36f71708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
