"""Add Phase 6 outfit recommendation fields

Revision ID: 021eba0e1985
Revises: f94bb5a3dca6
Create Date: 2026-06-13 02:46:30.813202
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '021eba0e1985'
down_revision: Union[str, None] = 'f94bb5a3dca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outfit_recommendations', sa.Column('ai_explanation', sa.Text(), server_default='This combination was selected based on your wardrobe preferences and color profile.', nullable=False))
    op.add_column('outfit_recommendations', sa.Column('weather_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('ix_outfit_recommendations_user_created', 'outfit_recommendations', ['user_id', sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outfit_recommendations_user_created', table_name='outfit_recommendations')
    op.drop_column('outfit_recommendations', 'weather_snapshot')
    op.drop_column('outfit_recommendations', 'ai_explanation')
    # ### end Alembic commands ###
