"""Add composite index on user_id and created_at

Revision ID: f94bb5a3dca6
Revises: dcc53558584e
Create Date: 2026-06-13 02:16:39.339836
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94bb5a3dca6'
down_revision: Union[str, None] = 'dcc53558584e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_clothing_items_user_created', 'clothing_items', ['user_id', sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clothing_items_user_created', table_name='clothing_items')
    # ### end Alembic commands ###
