"""add ai_usage_events

Revision ID: e225f9ce6a1b
Revises: 16bbe36364a0
Create Date: 2026-06-20 17:04:51.384863
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e225f9ce6a1b'
down_revision: Union[str, None] = '16bbe36364a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('credential_source', sa.String(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_events_created_at'), 'ai_usage_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_events_feature_name'), 'ai_usage_events', ['feature_name'], unique=False)
    op.create_index(op.f('ix_ai_usage_events_provider'), 'ai_usage_events', ['provider'], unique=False)
    op.create_index(op.f('ix_ai_usage_events_status'), 'ai_usage_events', ['status'], unique=False)
    op.create_index('ix_ai_usage_events_user_created', 'ai_usage_events', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_usage_events_user_created', table_name='ai_usage_events')
    op.drop_index(op.f('ix_ai_usage_events_status'), table_name='ai_usage_events')
    op.drop_index(op.f('ix_ai_usage_events_provider'), table_name='ai_usage_events')
    op.drop_index(op.f('ix_ai_usage_events_feature_name'), table_name='ai_usage_events')
    op.drop_index(op.f('ix_ai_usage_events_created_at'), table_name='ai_usage_events')
    op.drop_table('ai_usage_events')
    # ### end Alembic commands ###
