"""Add tool_invocations and reasoning to ChatMessage

Revision ID: 526c60d15a6e
Revises: ee9e72b43857
Create Date: 2026-06-15 23:57:22.641410
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '526c60d15a6e'
down_revision: Union[str, None] = 'ee9e72b43857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('tool_invocations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('chat_messages', sa.Column('reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'reasoning')
    op.drop_column('chat_messages', 'tool_invocations')
    # ### end Alembic commands ###
