"""Add intelligence tables

Revision ID: 9decf4f75368
Revises: 1a16a3b02411
Create Date: 2026-06-16 15:18:01.412597
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9decf4f75368'
down_revision: Union[str, None] = '1a16a3b02411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insight_quality_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('insight_type', sa.String(length=100), nullable=False),
    sa.Column('action_taken', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insight_quality_metrics_id'), 'insight_quality_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_insight_quality_metrics_user_id'), 'insight_quality_metrics', ['user_id'], unique=False)
    op.create_table('intelligence_feed_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('action_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('feed_category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_feed_items_id'), 'intelligence_feed_items', ['id'], unique=False)
    op.create_index(op.f('ix_intelligence_feed_items_user_id'), 'intelligence_feed_items', ['user_id'], unique=False)
    op.create_table('wardrobe_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('goal_type', sa.String(length=50), nullable=False),
    sa.Column('metric_target', sa.Float(), nullable=False),
    sa.Column('current_progress', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wardrobe_goals_id'), 'wardrobe_goals', ['id'], unique=False)
    op.create_index(op.f('ix_wardrobe_goals_user_id'), 'wardrobe_goals', ['user_id'], unique=False)
    op.create_table('wardrobe_opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wardrobe_opportunities_id'), 'wardrobe_opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_wardrobe_opportunities_user_id'), 'wardrobe_opportunities', ['user_id'], unique=False)
    op.create_table('weekly_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('coaching_advice', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_reports_id'), 'weekly_reports', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_reports_user_id'), 'weekly_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_reports_user_id'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_id'), table_name='weekly_reports')
    op.drop_table('weekly_reports')
    op.drop_index(op.f('ix_wardrobe_opportunities_user_id'), table_name='wardrobe_opportunities')
    op.drop_index(op.f('ix_wardrobe_opportunities_id'), table_name='wardrobe_opportunities')
    op.drop_table('wardrobe_opportunities')
    op.drop_index(op.f('ix_wardrobe_goals_user_id'), table_name='wardrobe_goals')
    op.drop_index(op.f('ix_wardrobe_goals_id'), table_name='wardrobe_goals')
    op.drop_table('wardrobe_goals')
    op.drop_index(op.f('ix_intelligence_feed_items_user_id'), table_name='intelligence_feed_items')
    op.drop_index(op.f('ix_intelligence_feed_items_id'), table_name='intelligence_feed_items')
    op.drop_table('intelligence_feed_items')
    op.drop_index(op.f('ix_insight_quality_metrics_user_id'), table_name='insight_quality_metrics')
    op.drop_index(op.f('ix_insight_quality_metrics_id'), table_name='insight_quality_metrics')
    op.drop_table('insight_quality_metrics')
    # ### end Alembic commands ###
