"""Add daily style brief table

Revision ID: ff971375d273
Revises: abffcd7e64b1
Create Date: 2026-06-17 22:19:37.861326
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff971375d273'
down_revision: Union[str, None] = 'abffcd7e64b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_style_briefs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('brief_date', sa.Date(), nullable=False),
    sa.Column('recommended_outfit', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weather_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('insight', sa.String(), nullable=False),
    sa.Column('style_tip', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('consecutive_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_style_briefs_brief_date'), 'daily_style_briefs', ['brief_date'], unique=False)
    op.create_index(op.f('ix_daily_style_briefs_user_id'), 'daily_style_briefs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_style_briefs_user_id'), table_name='daily_style_briefs')
    op.drop_index(op.f('ix_daily_style_briefs_brief_date'), table_name='daily_style_briefs')
    op.drop_table('daily_style_briefs')
    # ### end Alembic commands ###
