"""Add weather fields

Revision ID: 126baa415594
Revises: e1a71381841f
Create Date: 2026-06-27 22:55:28.785536
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126baa415594'
down_revision: Union[str, None] = 'e1a71381841f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('weather_city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('weather_country', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('weather_latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('weather_longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('weather_location_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weather_location_enabled')
    op.drop_column('users', 'weather_longitude')
    op.drop_column('users', 'weather_latitude')
    op.drop_column('users', 'weather_country')
    op.drop_column('users', 'weather_city')
    # ### end Alembic commands ###
