"""add_extended_profile_fields

Revision ID: 820fd5624517
Revises: 8027340db6ee
Create Date: 2026-06-18 18:58:31.226950
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '820fd5624517'
down_revision: Union[str, None] = '8027340db6ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('height_cm', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('body_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('fashion_experience', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('primary_style', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('profile_image_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('occupation', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('climate_region', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('favorite_colors', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('disliked_colors', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('preferred_fit', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('budget_preference', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'budget_preference')
    op.drop_column('users', 'preferred_fit')
    op.drop_column('users', 'disliked_colors')
    op.drop_column('users', 'favorite_colors')
    op.drop_column('users', 'climate_region')
    op.drop_column('users', 'occupation')
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'primary_style')
    op.drop_column('users', 'fashion_experience')
    op.drop_column('users', 'body_type')
    op.drop_column('users', 'height_cm')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
