"""Add OutfitFeedback and StyleProfileSnapshot models

Revision ID: ee9e72b43857
Revises: a5fd20a96452
Create Date: 2026-06-15 23:44:53.793928
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee9e72b43857'
down_revision: Union[str, None] = 'a5fd20a96452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style_profile_snapshots',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_name', sa.String(length=100), nullable=False),
    sa.Column('top_colors', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('top_categories', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('personalization_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_style_profile_snapshots_user_id'), 'style_profile_snapshots', ['user_id'], unique=False)
    op.create_index('ix_style_snapshots_user_created', 'style_profile_snapshots', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('outfit_feedback',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('outfit_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('feedback_source', sa.String(length=50), server_default='manual', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfit_recommendations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outfit_feedback_outfit_created', 'outfit_feedback', ['outfit_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_outfit_feedback_outfit_id'), 'outfit_feedback', ['outfit_id'], unique=False)
    op.create_index('ix_outfit_feedback_user_created', 'outfit_feedback', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_outfit_feedback_user_id'), 'outfit_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outfit_feedback_user_id'), table_name='outfit_feedback')
    op.drop_index('ix_outfit_feedback_user_created', table_name='outfit_feedback')
    op.drop_index(op.f('ix_outfit_feedback_outfit_id'), table_name='outfit_feedback')
    op.drop_index('ix_outfit_feedback_outfit_created', table_name='outfit_feedback')
    op.drop_table('outfit_feedback')
    op.drop_index('ix_style_snapshots_user_created', table_name='style_profile_snapshots')
    op.drop_index(op.f('ix_style_profile_snapshots_user_id'), table_name='style_profile_snapshots')
    op.drop_table('style_profile_snapshots')
    # ### end Alembic commands ###
