"""phase_6a

Revision ID: a5fd20a96452
Revises: 021eba0e1985
Create Date: 2026-06-15 22:15:12.779883
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5fd20a96452'
down_revision: Union[str, None] = '021eba0e1985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothing_items', sa.Column('purchase_price', sa.Float(), nullable=True))
    op.add_column('clothing_items', sa.Column('purchase_date', sa.Date(), nullable=True))
    op.add_column('clothing_items', sa.Column('worn_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('clothing_items', sa.Column('last_worn_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('outfit_recommendations', sa.Column('overall_score', sa.Integer(), nullable=True))
    op.add_column('outfit_recommendations', sa.Column('color_score', sa.Integer(), nullable=True))
    op.add_column('outfit_recommendations', sa.Column('weather_score', sa.Integer(), nullable=True))
    op.add_column('outfit_recommendations', sa.Column('occasion_score', sa.Integer(), nullable=True))
    op.add_column('outfit_recommendations', sa.Column('season_score', sa.Integer(), nullable=True))
    op.add_column('outfit_recommendations', sa.Column('utilization_score', sa.Integer(), nullable=True))
    op.add_column('outfit_recommendations', sa.Column('score_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outfit_recommendations', 'score_metadata')
    op.drop_column('outfit_recommendations', 'utilization_score')
    op.drop_column('outfit_recommendations', 'season_score')
    op.drop_column('outfit_recommendations', 'occasion_score')
    op.drop_column('outfit_recommendations', 'weather_score')
    op.drop_column('outfit_recommendations', 'color_score')
    op.drop_column('outfit_recommendations', 'overall_score')
    op.drop_column('clothing_items', 'last_worn_at')
    op.drop_column('clothing_items', 'worn_count')
    op.drop_column('clothing_items', 'purchase_date')
    op.drop_column('clothing_items', 'purchase_price')
    # ### end Alembic commands ###
