"""Add last_login_at and first_login_redirect_pending to User

Revision ID: 16bbe36364a0
Revises: 7850e19d153f
Create Date: 2026-06-20 04:05:59.669360
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16bbe36364a0'
down_revision: Union[str, None] = '7850e19d153f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('first_login_redirect_pending', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_login_redirect_pending')
    op.drop_column('users', 'last_login_at')
    # ### end Alembic commands ###
