"""Add ai_confidence and ai_generated to clothing_items

Revision ID: dcc53558584e
Revises: ec9614cd3d8a
Create Date: 2026-06-12 14:52:23.487352
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc53558584e'
down_revision: Union[str, None] = 'ec9614cd3d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothing_items', sa.Column('ai_confidence', sa.Integer(), nullable=True))
    op.add_column('clothing_items', sa.Column('ai_generated', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clothing_items', 'ai_generated')
    op.drop_column('clothing_items', 'ai_confidence')
    # ### end Alembic commands ###
