"""initial

Revision ID: 6350ed97dc17
Revises: 
Create Date: 2026-05-30 00:00:06.695427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6350ed97dc17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('auth_provider', sa.String(length=20), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('gender_preference', sa.String(length=50), nullable=True),
    sa.Column('style_preference', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('favorite_colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('common_occasions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_profile_complete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('clothing_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('front_image_key', sa.String(length=500), nullable=False),
    sa.Column('back_image_key', sa.String(length=500), nullable=True),
    sa.Column('label_image_key', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_key', sa.String(length=500), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('primary_color', sa.String(length=50), nullable=False),
    sa.Column('secondary_color', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('gender_fit', sa.String(length=50), nullable=True),
    sa.Column('material', sa.String(length=50), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('occasion', sa.String(length=50), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('usage_frequency', sa.String(length=50), nullable=True),
    sa.Column('wear_count', sa.Integer(), nullable=False),
    sa.Column('last_worn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_range', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('ai_detected', sa.Boolean(), nullable=True),
    sa.Column('ai_confidence', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clothing_items_is_deleted'), 'clothing_items', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_clothing_items_user_id'), 'clothing_items', ['user_id'], unique=False)
    op.create_table('outfit_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('top_item_id', sa.UUID(), nullable=True),
    sa.Column('bottom_item_id', sa.UUID(), nullable=True),
    sa.Column('footwear_item_id', sa.UUID(), nullable=True),
    sa.Column('accessory_item_id', sa.UUID(), nullable=True),
    sa.Column('occasion', sa.String(length=50), nullable=True),
    sa.Column('weather', sa.String(length=50), nullable=True),
    sa.Column('worn_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['accessory_item_id'], ['clothing_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bottom_item_id'], ['clothing_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['footwear_item_id'], ['clothing_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['top_item_id'], ['clothing_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfit_history_user_id'), 'outfit_history', ['user_id'], unique=False)
    op.create_table('saved_outfits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('top_item_id', sa.UUID(), nullable=True),
    sa.Column('bottom_item_id', sa.UUID(), nullable=True),
    sa.Column('footwear_item_id', sa.UUID(), nullable=True),
    sa.Column('accessory_item_id', sa.UUID(), nullable=True),
    sa.Column('occasion', sa.String(length=50), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['accessory_item_id'], ['clothing_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bottom_item_id'], ['clothing_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['footwear_item_id'], ['clothing_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['top_item_id'], ['clothing_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_outfits_user_id'), 'saved_outfits', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_outfits_user_id'), table_name='saved_outfits')
    op.drop_table('saved_outfits')
    op.drop_index(op.f('ix_outfit_history_user_id'), table_name='outfit_history')
    op.drop_table('outfit_history')
    op.drop_index(op.f('ix_clothing_items_user_id'), table_name='clothing_items')
    op.drop_index(op.f('ix_clothing_items_is_deleted'), table_name='clothing_items')
    op.drop_table('clothing_items')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
